#include<stdio.h>
int main()
{
    int n,a[100],i,max=0,temp,j,k;
    scanf("%d",&n);
 
    for(i=0;i<n;i++)
    {
        scanf("%d",&a[i]);
    }
       for(i=0;i<n;i++)
    {
        for(j=i+1;j<n;j++)
        {
            if(a[i]==a[j])   
            {
                for(k=j;k<n;k++)
                {
                    a[k]=a[k+1];
                }
                n--;
                j--;
            }            
        }
    }
    if(n<3)
    {
        printf("%d",a[n-1]);
    }
    else
    {
        for(i=0;i<n;i++)
        {
            for(j=i+1;j<n;j++)
            {
                if(a[i]==a[j])   
                continue;
                if(a[i]>a[j])
                {
                    temp=a[i];
                    a[i]=a[j];
                    a[j]=temp;
                }
                else
                continue;
            }
        }
        printf("%d",a[n-3]);
    }
}