#include<stdio.h>
int main()
{
    int n,i,a[100],j,c,max;
    scanf("%d",&n);
    for(i=0;i<n;i++)
    {
        scanf("%d",&a[i]);
    }
    for(i=0;i<n;i++)
    {
        if(a[i]==1)
        {
            c=1;
            for(j=i+1;j<n;j++)
            {
                if(a[i]==a[j])
                {
                    c++;
                }
                else
                {
                    break;
                }
            }
            if(c>max)
            {
                max=c;
            }
        }
    }
    printf("%d",max);
}