#include<stdio.h>
#include<math.h>
int main()
{
    int n,r,l,i,c,flag=0;
    scanf("%d%d",&r,&l);
    c=0;
    for(n=r;n<=l;n++)
    {
        if(n==1)
        {
            continue;
        }
        flag=0;
        for(i=2;i<=sqrt(n);i++)
        {
            if(n%i==0)
            {
                flag=1;
                break;
            }
        }
        if(flag==0)
        {
            c++;
        }
    }
    printf("%d",c);
}